theme: jekyll-theme-minimal
title: 'Single Cell RNA-Seq Analysis'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Schedule
    url: base/schedule

  - heading: Support
  - title: Slack
    url: base/slack
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links
  - title: GitHub repository
    url: https://github.com/ucdavis-bioinformatics-training/2023-December-Single-Cell-RNA-Seq-Analysis
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu

  - heading: Prerequisites
  - title: CLI
    url: base/cli_prerequisites
  - title: R
    url: base/r_prerequisites_fixed

  - heading: Data Reduction
  - title: Files and Filetypes
    url: data_reduction/filetypes
  - title: Project setup
    url: data_reduction/project_setup
  - title: Generating Expression Matrix
    url: data_reduction/Expression_Matrix

  - heading: scRNAseq Analysis
  - title: Prepare scRNAseq Analysis
    url: data_analysis/scrna_analysis_prepare
  - title: scRNAseq Analysis - PART1
    url: data_analysis/scRNA_Workshop-PART1_fixed
  - title: scRNAseq Analysis - PART2
    url: data_analysis/scRNA_Workshop-PART2_fixed
  - title: scRNAseq Analysis - PART3
    url: data_analysis/scRNA_Workshop-PART3_fixed
  - title: scRNAseq Analysis - PART4
    url: data_analysis/scRNA_Workshop-PART4_fixed
  - title: scRNAseq Analysis - PART5
    url: data_analysis/scRNA_Workshop-PART5_with_quizzes
  - title: scRNAseq Analysis - PART6
    url: data_analysis/scRNA_Workshop-PART6
  - title: scRNAseq Analysis - PART7
    url: data_analysis/scRNA_Workshop-PART7
